name: test_abaqus
archive: dropbox
stats: false
tasks:
  - name: generate_material_models
    method: default
    software: abaqus[2017]
    base:
      materials_list:
        - name: rigid
          elastic:
            youngs_modulus: 200000
            poisson_ratio: 0.3
        - name: euromat_A
          func_name: euromat_A
          temp: -91

  - name: generate_specimen_parts
    method: compact_tension_fracture
    software: abaqus[2017]
    base:
      dimension: 2
      mesh_definition:
        mesh_type: finite_radius_uniform     # finite_radius_fan | finite_radius_uniform
        crack_tip_radius_microns: 10
        fine_mesh_length: 0.2
        fine_mesh_element_length: 0.02
        fan_box_width: 8  # aproximate width of fan mesh in multiples of crack_tip_radius
        fan_box_num_side_elements: 3
      elem_type: CPE4  # C3D8R
      size_type: ct-1t
      fraction: half   # full | half | quarter
      specimen_material: euromat_A

  - name: generate_steps
    method: compact_tension_steps
    software: abaqus[2017]
    base:
      time_increment_definition:
        initial_time_increment: 0.02
        total_step_time: 1.0
        min_time_increment_allowed: 1e-08
        max_time_increment_allowed: 0.02
      applied_displacement: 0.001 # in mm    

  - name: simulate_deformation
    method: FE
    software: abaqus[2017]
    run_options:
      num_cores: 8
    base:
      memory: 20 GB
      # do_datacheck: true